
export const FETCH_ALL_TODOS = "FETCH_ALL_TODOS";
export const FETCH_ALL_TODOS_PENDING = "FETCH_ALL_TODOS_PENDING";
export const FETCH_ALL_TODOS_FULFILLED = "FETCH_ALL_TODOS_FULFILLED";
export const FETCH_ALL_TODOS_REJECTED = "FETCH_ALL_TODOS_REJECTED";

export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_TODO_PENDING = "COMPLETE_TODO_PENDING";
export const COMPLETE_TODO_FULFILLED = "COMPLETE_TODO_FULFILLED";
export const COMPLETE_TODO_REJECTED = "COMPLETE_TODO_REJECTED";

export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_PENDING = "DELETE_TODO_PENDING";
export const DELETE_TODO_FULFILLED = "DELETE_TODO_FULFILLED";
export const DELETE_TODO_REJECTED = "DELETE_TODO_REJECTED";

export const ADD_NEW_TODO = "ADD_NEW_TODO";
export const ADD_NEW_TODO_PENDING = "ADD_NEW_TODO_PENDING";
export const ADD_NEW_TODO_FULFILLED = "ADD_NEW_TODO_FULFILLED";
export const ADD_NEW_TODO_REJECTED = "ADD_NEW_TODO_REJECTED";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_REJECTED = "REGISTER_USER_REJECTED";

export const LOGOUT_USER = "LOGOUT_USER";
export const FORM_PANEL_UPDATE = "FORM_PANEL_UPDATE";
export const LOGIN_FORM_UPDATE = "LOGIN_FORM_UPDATE";
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM";
